language: haskell
before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - cabal update

install:
  - cabal configure $mode
  - cabal build

script:
  - $script && hlint src --cpp-define HLINT

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
