language: haskell
before_install:
  - cabal update

ghc:
  - "8.4"
  - "8.0"
  - "7.10"
  - "7.8"

install:
  - cabal install data-default
  - cabal configure --enable-tests && cabal build && cabal test
  - cabal haddock