language: haskell
before_install:
  - cabal update

install:
  - cabal build
  - cabal haddock

script:
  - $script && hlint src --cpp-define HLINT

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
